### ISSUE TITLE
Using dark titlebar negates tkcalender style

### ISSUE THREAD

**Issue by harisenthil1** [j4321/tkcalendar#103]
To make the title bar dark I use the below code
```python
import ctypes as ct
window.update()
DWMWA_USE_IMMERSIVE_DARK_MODE = 20
set_window_attribute = ct.windll.dwmapi.DwmSetWindowAttribute
get_parent = ct.windll.user32.GetParent
hwnd = get_parent(window.winfo_id())
rendering_policy = DWMWA_USE_IMMERSIVE_DARK_MODE
value = 2
 value = ct.c_int(value)
 set_window_attribute(hwnd, rendering_policy, ct.byref(value), ct.sizeof(value))
``` 
But when I use the code, the combobox that contains Tkcalender loses its styles and shows up as normal unstyled combobox

![image](https://github.com/j4321/tkcalendar/assets/96934076/0940d421-41a0-4935-aac8-9137b5182dac)

Fo reference, This is what it looks like without using the above code,
![image](https://github.com/j4321/tkcalendar/assets/96934076/ffec0e36-86f8-4fc2-81e9-adc2e4c79e04)

I'll also add the DateEntry element's code

```python
invoiceDateEntry=DateEntry(invoiceFrame,showothermonthdays=False,showweeknumbers=False,date_pattern='dd/mm/yyyy',month=(int(datetime.now().strftime('%m'))-1),year=(date.today().replace(day=1) - timedelta(days=1)).year)
invoiceDateEntry.grid(row=1,column=1,padx=30,pady=10, sticky="ew")
#invoiceNoEntry.bind('<Return>',lambda e: invoiceDateEntry.focus_set())
``` 
**Calendar opened (Without dark titlebar code):**

![image](https://github.com/j4321/tkcalendar/assets/96934076/b1971a1c-c205-4c52-9802-166ee26fe9ac)

**With Code:**

![Screenshot (20)](https://github.com/j4321/tkcalendar/assets/96934076/b4b9348c-26a6-4067-bbc9-437b79b3ead4)

The preset text is also white-colored, hence it is not visible. I use Sun Valley theme `sv_ttk`

**Comment by hariprasath112** [comment]
Found a way around to make it work. Used a library called `ntkutils` to set dark titlebar
```python
 import ntkutils
 ntkutils.dark_title_bar(root)
``` 
then made the window close and restart itself with the below code
```python
python = sys.executable
os.execl(python, python, * sys.argv)
```

**Comment by harisenthil1** [comment]
Found a way around to make it work. Used a library called `ntkutils` to set dark titlebar
```python
 import ntkutils
 ntkutils.dark_title_bar(root)
``` 
then made the window close and restart itself with the below code
```python
python = sys.executable
os.execl(python, python, * sys.argv)
```
