### ISSUE TITLE
Display events

### ISSUE THREAD

**Issue by BastienH** [j4321/tkcalendar#19]
Hi j4321,
First bravo for this nice piece of code !

I've been looking for a way to display events to the your calendar. For example birthdays or holidays, colorize them or write notes in the calendar, but I can't seem to find how to do that.
I'm wondering if you're already working on something alike?

To be sure, I'm new to github and coding so maybe there is a another way to ask you that then "opening a ticket" :) 

Anyway have a good day
Bastien

**Comment by j4321** [comment]
Hi Bastien,

Thanks. 

There is no way to add events in the calendar yet, though I had created something like that in a different [project](https://github.com/j4321/Scheduler) partly based on my calendar (This is a collection of desktop widgets that I created for my personal use and it is not really distribution ready yet). So, yes I can implement it and I'll try to add the feature to the next release.

Have a good day.

**Comment by BastienH** [comment]
Cool!

Well I'd be glad to help if you like. I can do small code, testing and debugging :)

Cya

**Comment by j4321** [comment]
Ok, I let you know when I have testable code. 

Right now I could use some help to name the functions to add / delete / edit events. Tkinter widgets already have `event_add` and `event_delete` methods, so I need to find names to avoid any confusion with GUI events.

**Comment by j4321** [comment]
If you want, you can try the code [here](https://github.com/j4321/tkcalendar/tree/events). There is a basic example in [`__main__.py`](https://github.com/j4321/tkcalendar/blob/events/tkcalendar/__main__.py).
