### ISSUE TITLE
Leap year error

### ISSUE THREAD

**Issue by bchip50** [j4321/tkcalendar#27]
Drop down displays 2/29/2000. This day didn't exist.

**Comment by j4321** [comment]
Figuring out whether 2000 is a leap year or not is a bit tricky, it is an exception of an exception. According to [Wikipedia](https://en.wikipedia.org/wiki/Leap_year):

> Every year that is exactly divisible by four is a leap year, except for years that are exactly divisible by 100, but these centurial years are leap years if they are exactly divisible by 400. For example, the years 1700, 1800, and 1900 were not leap years, but the years 1600 and 2000 were.

So 2/29/2000 actually existed.
