### ISSUE TITLE
pyinstaller compatability

### ISSUE THREAD

**Issue by tgikal** [j4321/tkcalendar#32]
I'm not sure where the problem is, but since pyinstaller works with basically every other module I'm using, I'm going to guess that this one is calling something in a way it doesn't like.

Currently this works great when ran as a python file, but when made into a .exe with pyinstaller, it fails to load past the tkcalendar calls.

build data seems to show a inability to find particular modules:
```
missing module named tkFont - imported by tkcalendar.calendar_ (optional)
missing module named ttk - imported by tkcalendar.dateentry (optional), tkcalendar.calendar_ (optional), tkcalendar.tooltip (optional)
```
Just putting this out there to see if anyone else has encountered this.

**Comment by tgikal** [comment]
Well, even removing those imports from the files and having no missing modules for tkcalendar appear still does not work in .exe format.

**Comment by j4321** [comment]
I am not a Windows user and I do not use pyinstaller so I am not sure I will be able to find out what is the issue here. 

But maybe this [question on StackOverflow](https://stackoverflow.com/questions/25733467/pyinstaller-no-module-named) is related. If this is the case, it means that pyinstaller does not detect correctly tkcalendar dependencies. According to one of the answers, you could try to put them in the spec file with:

- python 3:

        hiddenimports=["tkinter.ttk", "tkinter.font"]

- python 2:

        hiddenimports=["ttk", "tkFont"]

I hope it helps.

**Comment by tgikal** [comment]
Following the suggested items in the StackOverflow link, I packed it without --onefile, and without -w, and it looks like the error is to do with the babel module:

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1702, in __call__
  File "test.pyw", line 200, in Export
  File "site-packages\tkcalendar\dateentry.py", line 91, in __init__
  File "site-packages\tkcalendar\calendar_.py", line 212, in __init__
  File "site-packages\babel\dates.py", line 314, in get_day_names
  File "site-packages\babel\core.py", line 641, in days
  File "site-packages\babel\core.py", line 364, in _data
  File "site-packages\babel\localedata.py", line 111, in load
  File "site-packages\babel\localedata.py", line 111, in load
  File "site-packages\babel\localedata.py", line 117, in load
ModuleNotFoundError: No module named 'babel.numbers'
```

**Comment by j4321** [comment]
Have you tried to add babel in the hidden-modules?

**Comment by tgikal** [comment]
At this point I think I've found a similar issue between the pyinstaller and babel groups, looks like this is the workaround: https://github.com/python-babel/babel/issues/605#issue-371093845.

**Comment by tgikal** [comment]
Ok, can now confirm `pyinstaller.exe --hidden-import=babel.numbers` fixes the issue.
Thank you for your time and help, and I appreciate the work you've done with this module.

**Comment by VShkaberda** [comment]
I had the same problem. According to https://tekrecipes.com/2019/04/17/modulenotfounderror-no-module-named-babel-numbers/  I fixed this by adding `from babel.numbers import *` to the `calendar.py`. Maybe it is worth to consider to add this import permanently.

**Comment by jellisjo** [comment]
thank you ! i was having the same issue and got it fixed with pyinstaller --hidden-import=babel.number

**Comment by apocalypse2012** [comment]
This doesn't work any more. 

Why don't you just use the requirements file! This is insane.

**Comment by BrunoMazulo** [comment]
Thanks!! it worked for me -> pyinstaller.exe --hidden-import=babel.numbers yourscript.py

**Comment by apocalypse2012** [comment]
Well something isn't working. Maybe its virtual environments I don't know, but it fails every time.

**Comment by Sismo2003** [comment]
hey @apocalypse2012 did you got a solution? i have the same problem

**Comment by apocalypse2012** [comment]
Nope. Never did.Sent from my iPhoneOn Sep 1, 2023, at 6:53 PM, Alexis Ortiz ***@***.***> wrote:﻿
hey @apocalypse2012 did you got a solution? i have the same problem

**Comment by Baxrom97** [comment]
вввЯ
