### ISSUE TITLE
Wrong weekend days when using firstweekday='sunday'

### ISSUE THREAD

**Issue by handelo** [j4321/tkcalendar#37]
When you use the parameter firstweekday='sunday', Saturday and Sunday are still colored as the weekend days, instead of Friday and Saturday.
![WrongWeekendCalendar](https://user-images.githubusercontent.com/11184403/56089448-72c58580-5e9b-11e9-9722-15dd178bc58a.png)

**Comment by j4321** [comment]
I am French and therefore not used to have Sunday as the first day of the week, but from a quick Internet search, it seems to me that Americans color Saturday and Sunday, not Friday and Saturday.
For instance, I found the following calendar:
![calendar](http://www.calendarpedia.com/images/2019-calendar-usa.png)

**Comment by handelo** [comment]
Ah, I see. In my country the week starts on Sunday and the weekend days are Friday and Saturday, so I wrongly assumed this was unintentional.
In that case, is it possible to add an option to choose what days are colored as the weekend days?
