### ISSUE TITLE
Support for ttk style for dateEntry

### ISSUE THREAD

**Issue by Garrett-irl** [j4321/tkcalendar#42]
Any chance support could be added for the dateEntry widget when choosing a ttk theme. Seems ok on most but the "black" option has an error. When the date is picked the entry appear blank until highlighted. OS is Windows 10 python 3

**Comment by j4321** [comment]
I have tried the themes blue, alt, classic, ubuntu, keramik_alt, elegance, equilux, black, default, arc, radiance, plastik, aquativo, keramik, clam, winxpblue, kroc and clearlooks and the DateEntry adapts poorly only to the black theme. 

I don't have a lot of free time these days so this fix won't be a priority but you can manually change the foreground color of the DateEntry with:

``` python
style.configure('DateEntry', foreground='black')
```

**Comment by Garrett-irl** [comment]
Perfect workaround thanks for the advice.
