### ISSUE TITLE
Hide calendar bug

### ISSUE THREAD

**Issue by Tech-GS** [j4321/tkcalendar#51]
Pressing the Combobox list button again when the calendar is open does not hide it, but reopens it.

Solution to the problem in "tkcalendar.py":
``` python
    def _on_focus_out_cal(self, event):
        if self.focus_get() is not None:
            ...
        else:
            if 'active' in self.state():  # if xc <= x <= xc + w and yc <= y <= yc + h:
                self._calendar.focus_force()
            else:
            ...

```

**Comment by j4321** [comment]
Thanks for telling me. I had not notice because, like #49, it does not happen in Linux.

**Comment by Tech-GS** [comment]
Problem solved.
