### ISSUE TITLE
Added textvariable option

### ISSUE THREAD

**Issue by nprobert** [j4321/tkcalendar#6]
[tkcalendar.zip](https://github.com/j4321/tkcalendar/files/1708273/tkcalendar.zip)
I hacked tkcalendar.py to support the textvariable option to get it's initial value and to set it when the day is clicked.  Also added get_date() and set_date() methods to use when reading/writing config files.  I also needed to have multiple calendars up on the same frame.

**Comment by j4321** [comment]
Thanks for your interest in my calendar widget. I will take a look at your code. I guess from your profile that you are rather new to github. It would have been more practical if you had forked my project and submitted a pull request. But this is not a big problem, I will create a new branch with your code.

**Comment by j4321** [comment]
I am ok with adding a `textvariable` to the calendar, but I have a few comments about your code (see https://github.com/j4321/tkcalendar/pull/7). 
However I don't understand your last request:
>  I also needed to have multiple calendars up on the same frame.

You can put several calendar widget in a tkinter frame so I will need more details to understand what you want to do.

**Comment by nprobert** [comment]
Yeah, I'm fairly new to Git and Python.  I'm done with Perl if I can help it.
I am in the process of migrating from Subversion to Git for all my newer projects.  Let me fork it and put it in my changes and generate a pull request.  I need to learn this.
At first when I put multiple calendars up, the notification event was the same so I couldn't tell which calendar it was.  Using the textvariable solved my problem of getting the date in and out.

**Comment by j4321** [comment]
Ok, fine, let's do it that way, I'll put my comments on your pull request.
