### ISSUE TITLE
Calendar drop-down issue

### ISSUE THREAD

**Issue by vpdotta** [j4321/tkcalendar#66]
Hi!

First, thanks for the code!

Today I noticed an issue that was fixed on 1.6.0 (thanks again), when i changed from python 3.7.3 to 3.8.1.

It was ok, solved, but when i select the calendar the drop-down issue appears again.

![pyDateEntry](https://user-images.githubusercontent.com/25784401/71538541-891d4f80-290b-11ea-9eee-2363e22c7be6.png)

**Comment by vpdotta** [comment]
I've seen that you add those following lines

if self.winfo_toplevel().attributes('-topmost', _**True**_):
       self._top_cal.attributes('-topmost', True)
else:
       self._top_cal.attributes('-topmost', False)

Removing True from if, getting the value of -topmost from window solved the issue.

**Comment by j4321** [comment]
Thanks for pointing out the typo, I did some tests in Windows on a different machine and I introduced the error afterwards.
